<?PHP

$cardDetails = array(
    array("cardName" => "Citi® Double Cash ",
        "cardImage" => "http://cdn.comparecards.com/uploads/images/items/841.jpg",
        "cardLink" => "https://www.citi.com/credit-cards/credit-card-details/citi.action?ID=citi-double-cash-credit-card&category=savings-and-cash-back-credit-cards&afc=1A8&intc=7~7~67~1~MCT~1~CMSDefaultOffer~4T5ZM5R531A8111111W",
        "annaulSavings" => $CitiDCAnnualSaving,
        "feature1" => " Earn 1% cash back on every dollar you spend.",
        "feature2" => " Earn an additional 1% back for every dollar you pay off, a total of 2% Cash back on all purchases",
        "feature3" => " <span style = 'color:purple ; font-weight: bold'> No Annual Fee </span>",
        "feature4" => " 0% for 15 months on purchases and balance transfers, and then the ongoing APR of 13.24% - 23.24% Variable",
        "feature5" => " You can start redeeming Cash back with as little as $25 in rewards."
    ),
    array("cardName" => "Blue Cash Preferred® Card",
        "cardImage" => "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/CreditCards/img/Comparecards/blue_cash_pref_ant_176X111.gif",
        "cardLink" => "https://www.americanexpress.com/us/credit-cards/blue-cash-preferred?nc=yes&linknav=us-ccsg-cardshop-cm-viewallcards-learnmore",
        "annaulSavings" => $BlueCashPrefAnnaulSavings,
        "feature1" => " 6% Cash back at U.S. supermarkets up to $6,000 per year in purchases (then 1%).",
        "feature2" => " 3% Cash back at U.S. gas stations and at select U.S. department stores.",
        "feature3" => " <span style='color:red'> Annual fee of $75 per year. </span>",
        "feature4" => " Don’t be deterred by the $75 annual fee — spend just $25 a week on groceries and you’ve made up for the fee, not to mention the signup bonus.",
        "feature5" => " One-time $150 Cash back after you spend $1,000 in purchases on your new Card in your first 3 months."
    ),
    array("cardName" => "Barclaycard CashForward™ ",
        "cardImage" => "https://gif.barclaycardus.com/apply/img/ocb/cashforwardcardart.png",
        "https://www.barclaycardus.com/8291",
        "annaulSavings" => $BarclayCashForwardAnnualSaving,
        "feature1" => " Earn unlimited 1.5% cash rewards on every purchase.",
        "feature2" => " Every time you redeem, get a 5%cash rewards redemption bonus to use toward your next redemption.",
        "feature3" => " The minimum redemption amount is $50. You will need to spend $3,333.33 before you can get your 1.5% cash back. ",
        "feature4" => " <span style = 'color:purple; font-weight: bold'> No Annual Fee </span>",
        "feature5" => " One-time $100 cash back after you spend $500 in purchases on your new Card in your first 3 months."
    ),
    array("cardName" => "Capital One® Quicksilver®",
        "cardImage" => "https://c1.nerdwallet.com/images/11718_M.jpg",
        "cardLink" => "https://www.capitalone.com/credit-cards/quicksilver/",
        "annaulSavings" => $CapitaloneQSAnnualSaving,
        "feature1" => " Earn unlimited 1.5% Cash back on every purchase, every day.",
        "feature2" => " <span style = 'color:purple ; font-weight: bold'> No annual fee or foreign transaction fees.</span>",
        "feature3" => " No rotating categories or sign ups needed to earn cash rewards.",
        "feature4" => " One-time $100 Cash bonus after you spend $500 on purchases within the first 3 months.",
        "feature5" => " Get a 20% Statement Credit on Uber rides purchased with this card "
    ),
    array("cardName" => "BankAmericard Cash Rewards™",
        "cardImage" => "http://cdn.comparecards.com/uploads/images/items/1161.png",
        "cardLink" => "https://www.bankofamerica.com/credit-cards/products/cash-back-credit-card.go",
        "annaulSavings" => $BOACashRewardsAnnualSaving,
        "feature1" => " 3% Cash Back on gas purchases at the pump and",
        "feature2" => " 2% Cash Back at grocery stores for the first $1,500 in combined grocery/gas purchases each quarter.",
        "feature3" => " 1% Cash Back on all other purchases. ",
        "feature4" => " <span style = 'color:purple ; font-weight: bold'> No Annual Fee </span>",
        "feature5" => " One-time $100 Cash back after you spend $1,000 in purchases on your new Card in your first 3 months."
    ),
    array("cardName" => "U.S. Bank Cash+™",
        "cardImage" => "https://www.usbank.com/images/credit-card/cash-plus-detail.png",
        "cardLink" => "https://www.usbank.com/credit-cards/cash-plus-signature.html",
        "annaulSavings" => $USbankCashAnnualSaving,
        "feature1" => " 5% Cash back on your first $2,000 in combined net purchases each quarter on two categories which include telephone bills, departmental stores.",
        "feature2" => " 2% Cash back on your choice of one everyday category like gas, groceries or restaurants.",
        "feature3" => " 1% Cash back on everything else.",
        "feature4" => " <span style = 'color:purple; font-weight: bold'> No Annual Fee </span>",
        "feature5" => " 0% for 9 months on balance transfers, and then the ongoing APR of 13.24% - 24.24% Variable"
    ),
    array("cardName" => "Blue Cash Everyday® Card ",
        "cardImage" => "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/CreditCards/img/Comparecards/bluecash_evday_ant_176x111.gif",
        "cardLink" => "https://www.americanexpress.com/us/credit-cards/blue-cash-everyday?nc=yes&linknav=us-ccsg-cardshop-cm-viewallcards-learnmore",
        "annaulSavings" => $BlueCashAnnualSaving,
        "feature1" => "3% Cash Back at U.S. supermarkets, up to $6,000 per year in purchases (then 1%).",
        "feature2" => "2% Cash Back at U.S. gas stations; 2% Cash Back at select U.S. department stores.",
        "feature3" => "1% Cash Back on other purchases.",
        "feature4" => "<span style = 'color:purple ; font-weight: bold'> No Annual Fee </span>",
        "feature5" => "One-time $100 cash back after you spend $1,000 in purchases on your new Card in your first 3 months."
    ),
    array("cardName" => "Discover it® Chrome",
        "cardImage" => "https://www.discovercard.com/credit-cards/images/rewards/card-art-silver.png",
        "cardLink" => "https://www.discover.com/credit-cards/cash-back/chrome.html",
        "annaulSavings" => $DiscoverChromeAnnualSaving,
        "feature1" => "2% gas stations and restaurants up to $1,000 in combined purchases each quarter.",
        "feature2" => "1% Cash Back on all other purchases. ",
        "feature3" => "<span style = 'color:purple ; font-weight: bold'> No Annual Fee </span>",
        "feature4" => " <span style = 'color:purple ; font-weight: bold'> No foreign transaction fee </span>",
        "feature5" => "Currently offering double cash back for the first year your account is open"
    ),
    array("cardName" => 'PenFed Platinum Rewards',
        "cardImage" => "https://www.penfed.org/uploadedImages/Products/Credit_Cards/_images/Platinum-Rewards-Visa-Signature-Card-Art@2x.png",
        "cardLink" => "https://www.penfed.org/platinum-rewards-visa-signature/",
        "annaulSavings" => $PenfedVisaPlatAnnualSaving,
        "feature1" => " 5% Cash Back on gas purchases at the pump.",
        "feature2" => " 3% Cash Back at grocery stores or supermarkets.",
        "feature3" => " 1% Cash Back on all other purchases. ",
        "feature4" => " <span style = 'color:purple'> No Annual Fee </span>",
        "feature5" => " One-time $100 Cash back after you spend $1,000 in purchases on your new Card in your first 3 months."
    )
);
?>


