<?PHP

$cardDetails = array(
    array("cardName" => "Chase Sapphire Preferred® Card ",
        "cardImage" => "http://www.thesimpledollar.com/wp-content/uploads/2015/11/Chase-Sapphire-Preferred®-Card-BIG.png",
        "cardLink" => "https://creditcards.chase.com/a1/sapphire/apply50?CELL=6H8X&AFFID=flEXvhmGGcY-KDSuTnjT6Xn0Xc6ozxWLGw&pvid=A1A0015627274&jp_cmp=cc/307156/aff/3-10002570/na",
        "feature1" => " Earn 50,000 bonus points when you spend $4,000 on purchases in the first 3 months from account opening. That's $625 in travel when you redeem through Chase Ultimate Rewards®. Earn 5,000 bonus points after you add the first authorized user and make a purchase in the first 3 months from account opening.",
        "feature2" => " 2X points on travel and dining at restaurants & 1 point per dollar spent on all other purchases",
        "feature3" => " <span style = 'color:purple ; font-weight: bold'> Introductory Annual Fee of $0 the first year, then $95 </span>",
        "feature4" => " There is no introductory 0% APR offer with this card",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country"
    ),
    array("cardName" => "Barclaycard Arrival Plus™ World Card",
        "cardImage" => "http://www.thesimpledollar.com/wp-content/uploads/2015/11/Barclaycard-Arrival-Plus™-World-Elite-MasterCard®-BIG.png",
        "cardLink" => "http://www.findmybarclaycard.com/barclaycard-credit-cards/?campaignId=2165&shopperid=&cellNumber=1&referrerid=CFOPP_A2A0014685911_36153&referrerid=CFOPP_A2A0014685911_36153&publisherid=&advertisementid=",
        "feature1" => " Earn 40,000 bonus miles after you spend $3,000 on purchases in the first 90 days - that's enough to redeem for a $400 travel statement credit.",
        "feature2" => " Earn 2X miles on all purchases.Get 5% miles back to use toward your next redemption, every time you redeem.",
        "feature3" => " <span style='color:purple ; font-weight: bold'> Introductory Annual Fee of $0 the first year, then $89</span>. There is another version of this card whcih does carry annaul fee, however we will get less sign-up bonus.",
        "feature4" => " 0% introductory APR for 12 months for each Balance Transfer made within 45 days of account opening",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country"
    ),
    array("cardName" => "Citi ThankYou® Premier Card",
        "cardImage" => "https://www.citi.com/CRD/images/card_no_reflection/citi-thankyou-premier-credit-card.jpg",
        "cardLink" => "https://www.citicards.com/cards/credit/application/flow.action?app=UNSOL&t=t&sc=4MMZ5M86&m=11C2M10803W&B=C&ID=3131&uc=EM7&ProspectID=P4RF4Si2ljFd1D110j6GWE9iOcTzWLVq&intc=7~7~66~1~PDP~1~EM_P_TYPM_02162_D1*PDP**S*~4MMZ5M8611C2M10803W",
        "feature1" => " Earn 50,000 bonus ThankYou Points after $3,500 in purchases within the first 3 months of account opening - redeemable for $500 in gift cards, $625 for airfare, or other great rewards.",
        "feature2" => " 3 ThankYou Points per $1 spent on travel including gas, airfare, hotels, cruises, car rental agencies, travel agencies, railways, public transportation, tolls, taxis, parking and much more. 2 ThankYou Points per $1 spent on dining out and entertainment.",
        "feature3" => " <span style='color:purple ; font-weight: bold'> Introductory Annual Fee of $0 the first year, then $95</span>",
        "feature4" => " There is no introductory 0% APR offer with this card",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country"
   ),
    array("cardName" => "Venture From Capital One™",
       "cardImage" => "https://www.capitalone.com/media/graphic-logo/credit-cards/card-art/www-venture-visa-sig-flat-9-14.png",
        "cardLink" => "https://www.capitalone.com/credit-cards/venture/",
       "feature1" => " Earn 40,000 bonus ThankYou Points after $3,00 in purchases within the first 3 months of account opening - redeemable for $400 in travel.",
        "feature2" => " Get unlimited 2X miles—that's 2 miles for every dollar you spend on purchases, every day ",
        "feature3" => " <span style='color:purple ; font-weight: bold'> Introductory Annual Fee of $0 the first year, then $59</span>",
        "feature4" => " There is no introductory 0% APR offer with this card",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country"
   ),
    array("cardName" => "BankAmericard Travel Rewards® Card",
        "cardImage" => "https://www.bankofamerica.com/content/images/ContextualSiteGraphics/CreditCardArt/en_US/CardProject/bac_cards_branded/bankamericard-travel-rewards-credit-card-small.png",
        "cardLink" => "https://consumer.bankofamerica.com/USCCapp/Ctl/entry?sc=VACJA7&GV10=H%7C870%7C7402814&GV11=H%7C871%7C12465098&GV12=H%7C940%7CCJ_defaultmp_BankAmericardTravelRewards#b",
       "feature1" => " 20,000 online bonus points after you make at least $1,000 in purchases in the first 90 days - which can be redeemed for a $200 statement credit toward travel purchases.",
       "feature2" => " Get unlimited 2X points for every dollar you spend on purchases, every day.",
        "feature3" => " <span style='color:purple ; font-weight: bold'> No anual fee</span>",
        "feature4" => " Introductory 0%† APR for your first 12 billing cycles for purchases.",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country"
   ),
    array("cardName" => "Discover it® Miles",
       "cardImage" => "https://www.discovercard.com/credit-cards/images/rewards/miles-it-card-art.png",
        "cardLink" => "https://www.discovercard.com/application/displayLanding?pageFileId=listingsite-miles&sc=KD6S&iq_id=a1A2A0014688688&cmpgnid=ls-dca-flx-consumer-miles-kd6s-dtop&pid=36153",
       "feature1" => " No sign-up bonus, however rewards earned will be doubled.So if you've earned 20,000 Miles, we'll double it to 40,000 Miles - Automatically. Only for new cardmembers.",
        "feature2" => " Get unlimited 1.5X miles for every dollar you spend on purchases, every day. ",
        "feature3" => " <span style='color:purple ; font-weight: bold'> No Annaul Fee.</span>",
        "feature4" => " Introductory 0%† APR for your first 12 billing cycles for purchases.",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country, however Discover card acceptance is less outside of US."
    ),
    array("cardName" => "Penfed Travel Rewards CARD",
       "cardImage" => "https://www.penfed.org/uploadedImages/Products/Credit_Cards/_images/AMEX-Travel-Card-Art@2x.png",
        "cardLink" => "https://www.penfed.org/travel-rewards-american-express/",
       "feature1" => " 20,000 BONUS POINTS when you spend $2,500 within 3 months",
        "feature2" => " Get unlimited 1.5X miles for every dollar you spend on purchases, every day. ",
        "feature3" => " <span style='color:purple ; font-weight: bold'> No Annaul Fee.</span>",
        "feature4" => " Introductory 0%† APR for your first 12 billing cycles for balance tarnsfers only.",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country."
    ),
    array("cardName" => "Platinum Card® from AmEx",
       "cardImage" => "https://icm.aexp-static.com/Internet/Acquisition/US_en/AppContent/CreditCards/img/Comparecards/chg_plat_176x111.gif",
        "cardLink" => "https://www.americanexpress.com/us/credit-cards/platinum?nc=yes&linknav=us-ccsg-cardshop-cm-viewallcards-learnmore",
       "feature1" => " Get 40,000 points after you use your new Card to make $3,000 in purchases in your first 3 months.",
        "feature2" => " $200 Airline Fee Credit, Fee Credit for Global Entry or TSA Pre✓TM, Airport Lounge Access and Priority Pass™ Select and many other top class add on with this card. ",
        "feature3" => " <span style='color:Red ; font-weight: bold'> The annual fee for the Platinum Card is $450.</span>",
        "feature4" => " No 0% APR introductory offer with this card",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country."
    ),
    array("cardName" => "U.S. Bank FlexPerks® Travel Rewards",
       "cardImage" => "https://www.usbank.com/images/credit-card/flexperks-travel-rewards-visa-signature-credit-card.png",
        "cardLink" => "https://www.usbank.com/credit-cards/flexperks-travel.html",
       "feature1" => " Earn 20,000 enrollment FlexPoints with spend $3,500 in net purchases on your card within four months of account opening.Only 20,000 FlexPoints = up to a $400 ticket.",
        "feature2" => " Double FlexPoints on the category you spend the most on (gas, groceries or airlines) and most cell phone expenses. ",
        "feature3" => " <span style='color:purple ; font-weight: bold'> No Annaul Fee.</span>",
        "feature4" => " No 0% APR introductory offer with this card",
        "feature5" => " Travel and shop with confidence with premium Travel and Purchase Protection Benefits, including Trip Cancellation/Trip Interruption Insurance, Auto Rental Collision Damage Waiver, Purchase Protection and more",
        "feature6" => " No foreign transaction fees on anything you buy while in another country."
    )
);
?>


